name: torrent_parser
description: >
  This library contains various utility to validate and parse .torrent files. 
version: 1.1.1
author: xuty <xty50337@hotmail.com>
homepage: https://github.com/xtyxtyx/torrent_parser

environment:
  sdk: '>=2.2.0 <3.0.0'

executables:
  tp: parser

dependencies:
  json_annotation: ^2.0.0
  torrent_bencode: ^0.1.0
  convert: ^2.0.0
  path: ^1.6.0
  crypto: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0