name: torrent_parser
description: Utility to parse .torrent files.
version: 0.1.0
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'
  path: any

dependencies:
  json_annotation: ^2.0.0
  convert: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
